### ISSUE TITLE
Job / build reliable notifies

### ISSUE THREAD

**Issue by parsley42** [lnxjedi/gopherbot#102]
Add new `Notifies: [ "alice", "bob" ]` to TaskSpec for jobs and repositories. Users in a Notify must be in the `UserRoster`, or maybe a `Contacts:` section, e.g.:
```yaml
Contacts:
- Name: admins
  Users: [ "alice", "bob" ]
  Email: adminlist@my.org
```
