### ISSUE TITLE
External task environment configuration

### ISSUE THREAD

**Issue by parsley42** [lnxjedi/gopherbot#96]
Administrators should be able to e.g. set the PATH with a stanza like:
```yaml
ExternalEnvironment:
- Name: PATH
  Value: /usr/bin:/usr/bin:/opt/gopherbot
```
